/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const AppHelloWorldResult = IDL.Record({ 'id' : IDL.Principal });
  
  return IDL.Service({
    'app_hello_world' : IDL.Func([], [AppHelloWorldResult], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };