// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck

import type {_SERVICE as SatelliteActor} from './satellite.did';
import {idlFactory} from './satellite.factory.did.js';
import {getSatelliteExtendedActor} from '@junobuild/core';
import {schemaToIdl, schemaFromIdl} from '@junobuild/schema/utils';
import {j} from '@junobuild/schema';

const AppHelloWorldResultSchema = j.strictObject({id: j.principal()});

const helloWorld = async (): Promise<j.infer<typeof AppHelloWorldResultSchema>> => {
	const {app_hello_world} = await getSatelliteExtendedActor<SatelliteActor>({idlFactory});
	const idlResult = await app_hello_world();

	const result = schemaFromIdl({schema: AppHelloWorldResultSchema, value: idlResult});
	return AppHelloWorldResultSchema.parse(result);
};

export const functions = {
	helloWorld
};